#! /bin/sh

sxhkd &
picom &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config -m ^1 top_padding 26
bspc config -m ^1 bottom_padding 1
bspc config -m ^1 left_padding 1
bspc config -m ^1 right_padding 1

bspc config -m ^2 top_padding 1
bspc config -m ^2 bottom_padding 1
bspc config -m ^2 left_padding 1
bspc config -m ^2 right_padding 1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xmodmap ~/.dotfiles/misc/.xmodmap
feh --bg-scale ~/Pictures/Wallpapers/神奇时刻\ ɽ\ 城堡\ 4k壁纸_彼岸图网.jpg

